name: Terraform Apply
description: "Apply terraform changes"
runs:
  using: "composite"
  steps:
    - name: Terraform setup
      uses: ./.github/actions/terraform
    - name: Terraform Apply
      shell: bash
      run: ./tf/apply.sh