name: Terraform Apply
description: "Apply terraform changes"
runs:
  using: composite
  steps:
    - name: Prepare terraform
      uses: ./.github/actions/terraform

    - name: Terraform Apply
      shell: bash
      run: ./tf/apply.sh