package main

import (
	"context"
	"log"
	"os"

	"github.com/metalblueberry/acnil-bot/pkg/acnil"
)

const (
	SheetID = "1WFJL0tNJ21XtHfy6ksJvRe5rSUeTG44BmQbeEWYo4Y0"
)

// Generated by https://quicktype.io

func main() {

	// Prints the names and majors of students in a sample spreadsheet:
	// readRange := "Historial de prestamos!A:C"
	// insert := &sheets.ValueRange{}
	// insert.Values = append(insert.Values, []interface{}{"hello", "testing", "insert"})
	srv, err := acnil.CreateClientFromCredentals(context.Background(), "credentials.json")
	if err != nil {
		panic(err)
	}

	ctx := context.Background()

	db := acnil.GameDatabase{
		SRV:       srv,
		ReadRange: "A:H",
		Sheet:     "Juegos de mesa",
		SheetID:   SheetID,
	}
	log.Println(os.Args)
	list, err := db.Find(ctx, os.Args[1])
	if err != nil {
		panic(err)
	}

	log.Println(list)

	for _, g := range list {
		g.Holder = os.Args[2]
		log.Println(g)
		err = db.Update(ctx, g)
		if err != nil {
			panic(err)
		}
	}

}
