name: Terraform Delete
description: "Apply terraform changes"
runs:
  using: composite
  steps:
    - name: Prepare terraform
      uses: ./.github/actions/terraform

    - name: Terraform Delete
      shell: bash
      run: ./tf/delete.sh
