# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI/CD

on:
  push:
    branches: [ "master" ]

env:
  AUDIT_SHEET_ID: ${{ secrets.AUDIT_SHEET_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SHEETS_EMAIL: ${{ secrets.SHEETS_EMAIL }}
  SHEETS_PRIVATE_KEY: ${{ secrets.SHEETS_PRIVATE_KEY }}
  SHEETS_PRIVATE_KEY_ID: ${{ secrets.SHEETS_PRIVATE_KEY_ID }}
  SHEET_ID: ${{ secrets.SHEET_ID }}
  TOKEN: ${{ secrets.TOKEN }}
  WEBHOOK_SECRET_TOKEN: ${{ secrets.WEBHOOK_SECRET_TOKEN }}
  JUEGATRON_SHEET_ID: ${{ secrets.JUEGATRON_SHEET_ID }}


jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:
    - name: Check out repository
      uses: actions/checkout@v4   

    - name: Build binaries
      uses: ./.github/actions/build

    - name: Terraform Apply
      if: "contains(github.event.head_commit.message,'tf:apply')"
      uses: ./.github/actions/apply

    - name: Terraform Plan
      if: "contains(github.event.head_commit.message,'tf:plan')"
      uses: ./.github/actions/plan

    - name: Terraform Delete
      if: "contains(github.event.head_commit.message,'tf:delete')"
      uses: ./.github/actions/delete