name: Terraform Destroy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: Plan / Apply
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Terraform 1.5.7
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7


    - name: Terraform Init
      id: init
      run: terraform -chdir=./tf init
      continue-on-error: true

    - name: Terraform Workspace
      id: workspace
      run: terraform -chdir=./tf workspace select production

    - name: Terraform Apply
      run: ./tf/destroy.sh