name: Terraform Apply

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AUDIT_SHEET_ID: ${{ secrets.AUDIT_SHEET_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SHEETS_EMAIL: ${{ secrets.SHEETS_EMAIL }}
  SHEETS_PRIVATE_KEY: ${{ secrets.SHEETS_PRIVATE_KEY }}
  SHEETS_PRIVATE_KEY_ID: ${{ secrets.SHEETS_PRIVATE_KEY_ID }}
  SHEET_ID: ${{ secrets.SHEET_ID }}
  TOKEN: ${{ secrets.TOKEN }}
  WEBHOOK_SECRET_TOKEN: ${{ secrets.WEBHOOK_SECRET_TOKEN }}

jobs:
  terraform:
    name: Apply
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: ./.github/actions/terraform

    - name: Terraform Apply
      run: ./tf/apply.sh