name: Terraform Debug Plan

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AUDIT_SHEET_ID: ${{ secrets.AUDIT_SHEET_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SHEETS_EMAIL: ${{ secrets.SHEETS_EMAIL }}
  SHEETS_PRIVATE_KEY: ${{ secrets.SHEETS_PRIVATE_KEY }}
  SHEETS_PRIVATE_KEY_ID: ${{ secrets.SHEETS_PRIVATE_KEY_ID }}
  SHEET_ID: ${{ secrets.SHEET_ID }}
  TOKEN: ${{ secrets.TOKEN }}


jobs:
  terraform:
    name: Plan / Apply
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Terraform 1.5.6
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6
        terraform_wrapper: false

    - name: Terraform Init
      id: init
      run: terraform -chdir=./tf init

    - name: Terraform Workspace
      id: workspace
      run: terraform -chdir=./tf workspace select production

    - name: Terraform Plan
      id: plan
      run: |
        terraform -chdir=./tf output function_url
        FUNCTION_URL=`terraform -chdir=./tf output function_url`
        echo  ""
        echo  "Configure webhook to $FUNCTION_URL"
        curl -H "Content-Type: application/json" -X POST "https://enoh55u95nuym.x.pipedream.net" -d "{
            \"url\": $FUNCTION_URL
            }"
