name: Terraform Apply

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AUDIT_SHEET_ID: ${{ secrets.AUDIT_SHEET_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SHEETS_EMAIL: ${{ secrets.SHEETS_EMAIL }}
  SHEETS_PRIVATE_KEY: ${{ secrets.SHEETS_PRIVATE_KEY }}
  SHEETS_PRIVATE_KEY_ID: ${{ secrets.SHEETS_PRIVATE_KEY_ID }}
  SHEET_ID: ${{ secrets.SHEET_ID }}
  TOKEN: ${{ secrets.TOKEN }}
  WEBHOOK_SECRET_TOKEN: ${{ secrets.WEBHOOK_SECRET_TOKEN }}

jobs:
  terraform:
    name: Apply
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18.4'

    - name: Use Terraform 1.5.7
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
        terraform_wrapper: false

    - name: Cache Terraform
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-build-terraform-cache
        restore-keys: |
          ${{ runner.os }}-build-terraform-cache
          ${{ runner.os }}-build-
          ${{ runner.os }}-
        path: |
          ./tf/.terraform

    - name: Terraform Init
      id: init
      run: terraform -chdir=./tf init

    - name: Terraform Workspace
      id: workspace
      run: terraform -chdir=./tf workspace select production
    - name: Debug
      run: echo $WEBHOOK_SECRET_TOKEN

    - name: Terraform Apply
      run: ./tf/apply.sh